add user repository
genesis-tech-tribe/nishiki-backend pull request #146
Opened 2023-12-11 09:49 UTC by hitohata

## Overviews of implementation

Added the user repository.

## Review points

This PR uses the repository error, which was created in #145.

2023-12-13 09:19 UTC, taniguchiiqqq requested changes
LGTM. Thank you for updating package.json!
Don't we write test codes for repository implementation? IMO, it is not necessary or at least can be done later because it doesn't have domain knowledge.
I like the createUserObject is written in repository layer as we talked before. 👍

2023-12-13 09:19 UTC, taniguchiiqqq commented on backend/main/src/Shared/Adapters/DynamoClient.ts
The same file exist in `backend/main/src/Shared/Adapters/DB/`, so this one should be deleted. sorry, it should be caused by my late PR review 🙏

2023-12-13 09:26 UTC, hitohata commented
@taniguchiiqqq 
Thank you for your review.

> Don't we write test codes for repository implementation? IMO, it is not necessary or at least can be done later because it doesn't have domain knowledge.

Yes, that's why I didn't implement tests. This repository has little logic, it's just a wrapper of the NishikiTable Client.

2023-12-13 09:29 UTC, taniguchiiqqq commented
@hitohata 
Got it! I'm relieved we are on the same page.

2023-12-14 03:15 UTC, hitohata commented on backend/main/src/Shared/Adapters/DynamoClient.ts
@taniguchiiqqq 
I cannot figure out what file is mentioned. Do you mind if I ask you to specify the exact files?

2023-12-14 09:07 UTC, taniguchiiqqq commented on backend/main/src/Shared/Adapters/DynamoClient.ts
@hitohata 
I mean these two files.
`backend/main/src/Shared/Adapters/DynamoClient.ts`
`backend/main/src/Shared/Adapters/DB/DynamoClient.ts`
![image](https://github.com/genesis-tech-tribe/nishiki-backend/assets/70570221/79959d51-1736-44eb-b960-24a13ac44e61)

2023-12-14 09:55 UTC, hitohata commented on backend/main/src/Shared/Adapters/DynamoClient.ts
@taniguchiiqqq 
Thank you. I got it.
I deleted it.

2023-12-14 09:56 UTC, hitohata commented
I resolved the issues you pointed out.
Please check it and approve this PR.

2023-12-14 10:00 UTC, taniguchiiqqq approved these changes

2023-12-14 10:00 UTC, merged