Added the get user endpoint
genesis-tech-tribe/nishiki-backend pull request #219
Opened 2024-01-05 20:28 UTC by hitohata

## Overviews of implementation

Added the `get user endpoint`

## Review points

- I implemented the find user query
- I removed the find use case since the query took place its role.
- I added adapters of Hono

2024-01-06 09:38 UTC, taniguchiiqqq requested changes
Thank you for implementing! It looks good to me except for minor things.

2024-01-06 09:38 UTC, taniguchiiqqq commented on backend/main/src/Shared/Adapters/HonoAdapter.ts
> + * This returns 200 Bad Request.
This comment should be 200 Ok

2024-01-06 09:38 UTC, taniguchiiqqq commented on backend/main/src/User/Controllers/FindUserController.ts
> + * If a list of user IDs is given, the controller will return a list of user data.
Do we need to care about finding users' data cases? I think the group's query need to implement somehow to get users from DB, but findUserQuery is used only for getting one user's data.

2024-01-06 09:38 UTC, taniguchiiqqq commented on backend/main/src/User/Query/FindUser/FindUserQuery.ts
> +}
I think you don't need to return `emailAddress` for this query
https://genesis-tech-tribe.github.io/nishiki-documents/web-api/#tag/user/paths/~1users~1%7BuserId%7D/get

2024-01-07 01:29 UTC, hitohata commented on backend/main/src/User/Controllers/FindUserController.ts
> + * If a list of user IDs is given, the controller will return a list of user data.
I suppose that from the point of view of the group, this controller works as a repository. So, I implemented querying users' data. Is it redundant?

2024-01-07 01:31 UTC, hitohata commented on backend/main/src/Shared/Adapters/HonoAdapter.ts
> + * This returns 200 Bad Request.
I've fixed it. Sorry, sir.

2024-01-07 01:39 UTC, hitohata commented on backend/main/src/User/Query/FindUser/FindUserQuery.ts
> +}
I removed the email address [here](https://github.com/genesis-tech-tribe/nishiki-backend/pull/219/files#diff-2b7f522bbbdb81ff0ca702f6230d2b7ce2a3a5d379b7b8609b1667d5ac15bc35R53). Related to the above comment, for the future use, I left it in the controller.
However, as you point out, I feel this is against the YAGNI. Should I remove an email address here? Please tell me your opinion.

2024-01-07 09:04 UTC, taniguchiiqqq commented on backend/main/src/User/Query/FindUser/FindUserQuery.ts
> +}
Oh I see. For me, it's more straightforward to remove it here for now because the email address isn't used now, as you said.

2024-01-07 22:02 UTC, hitohata commented
@taniguchiiqqq 
I've removed the querying multiple users. Could you review it?

2024-01-08 00:15 UTC, taniguchiiqqq approved these changes
Thank you!! LGMT

2024-01-08 03:04 UTC, merged