Added delete user endpoint
genesis-tech-tribe/nishiki-backend pull request #318
Opened 2024-03-10 21:30 UTC by hitohata

## Overviews of implementation

Added a delete user endpoint

## Review points

Check the test if this is enough

2024-03-14 22:25 UTC, taniguchiiqqq approved these changes
Thank you so much for implementing this feature. And so sorry for the late review. I think the test cases for the abnormal systems is enough.

2024-03-14 22:25 UTC, taniguchiiqqq commented on backend/main/src/Services/DeleteUserService/DeleteUserService.ts
> + * The groups and containers that are possessed by only this user.
To make it clear, it seems better to be explicit that the groups and containers are deleted.
```suggestion
 * The groups and containers are deleted when they are possessed by only this user.
```

2024-03-14 22:25 UTC, taniguchiiqqq commented on backend/main/src/Services/DeleteUserService/DeleteUserService.ts
> +	targetUserId: string;
I think the roles of each prop are opposite. targetUserId is the target user of deletion specified by path parameter.

2024-03-14 22:25 UTC, taniguchiiqqq commented on backend/main/src/Services/DeleteUserService/DeleteUserService.ts
> +		// check the requested user token and the user token's one
I feel it's better to use the word user ID cuz the comparison is not about tokens but IDs.
```suggestion
		// check the requested user ID is the same as the user ID from the auth token.
```

2024-03-14 22:25 UTC, taniguchiiqqq commented on backend/main/src/Services/DeleteUserService/DeleteUserService.ts
> +		// check if the user is the owner of the group
Could you change this comment? cuz this check is in the `removeUserFromNishiki` function. So maybe this comment may suppose to be `check if the user exist`

2024-03-14 22:25 UTC, taniguchiiqqq commented on backend/main/src/Services/DeleteUserService/DeleteUserService.ts
> +		const userIdOrError = UserId.create(input.userId);
I think it should be targetUserId.

2024-03-14 22:26 UTC, taniguchiiqqq requested changes
Sorry I mistakenly approved, please check the comments

2024-03-15 20:28 UTC, hitohata commented
@taniguchiiqqq 
Thank you for your comment. I've updated. Could you please check it when you have a free time?

2024-03-16 01:30 UTC, taniguchiiqqq approved these changes
Thanks!! LGTM

2024-03-16 02:04 UTC, merged