84 create a main function api document
genesis-tech-tribe/nishiki-backend pull request #99
Opened 2023-11-15 05:03 UTC by hitohata

## Overviews of implementation

Added an OpenAPI document in the main project.
Changed the typedoc directory.

## Review points

Run docker-compose command

2023-11-16 08:42 UTC, taniguchiiqqq requested changes
Thank you! I ensured that the web-api doc works. Can you just add a docker compose command to readme?

I found the following errors happened when I run the container after I did once like `docker compose up`. Can you check if it happens in your environment? ( and sorry I didn't noticed in the creating type doc container PR. )
> nishiki-backend-project-main-type-doc-1      | mv: inter-device move failed: './docs/interfaces' to '/build/interfaces'; unable to remove target: Directory not empty

2023-11-16 08:47 UTC, taniguchiiqqq requested changes

2023-11-16 08:47 UTC, taniguchiiqqq commented on backend/main/web-api/main-web-api.yaml
> +        - user
I found a Semantic Error here. It needs to define the declared path parameter "userId" in this delete operation.
```yml
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
```

2023-11-16 16:59 UTC, hitohata commented
@taniguchiiqqq 
>I found the following errors happened when I run the container after I did once like docker compose up. Can you check if it happens in your environment? ( and sorry I didn't noticed in the creating type doc container PR. )

Thank you for reviewing.
It seems that it comes from the target directory is not empty. This is no problem when deploying because the target directory which is in the docker memory is initialized every time. But, yes, it's not comfortable for us. So, I'll manage it somehow.

2023-11-17 00:35 UTC, taniguchiiqqq commented
@hitohata 
ohh sorry, I forgot it's mainly for the GithubPages. I'll approve just after you fix the semantic error.

2023-11-17 00:40 UTC, hitohata commented
@taniguchiiqqq 
OK, I fixed it.

2023-11-17 00:41 UTC, taniguchiiqqq approved these changes

2023-11-17 00:42 UTC, merged